services:
  socio-backend-dev:
    image: socio-backend
    build: 
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
    ports:
      - 3001:3000
    container_name: socio-be-dev-ctn
